extends Node

const VANILLA = {
	"name":"ΔV: Rings of Saturn",
	"priority":0,
	"version_data":{
		"version_major":1,
		"version_minor":0,
		"version_bugfix":0,
		"version_metadata":"",
		"full_version_array":[1,0,0],
		"full_version_string":"1.0.0",
		"legacy_mod_version":"1.0.0"
	},
	"mod_icon":{
		"has_icon_file":true,
		"icon_path":"res://HevLib/ui/mod_menu/vanilla/vanilla_icon.stex"
	},
	"library_information":{
		"is_a_library":false,
		"keep_library_hidden":true
	},
	"node":null,
	"manifest":{
		"has_manifest":true,
		"manifest_version":2.1,
		"manifest_data":{
			"mod_information":{
				"name":"ΔV: Rings of Saturn",
				"id":"kodera.vanilla",
				"description":"HEVLIB_VANILLA_DESCRIPTION",
				"brief":"HEVLIB_VANILLA_BRIEF",
				"author":"Kodera Software",
				"credits":[]
			},
			"version":{
				"version_major":1,
				"version_minor":0,
				"version_bugfix":0,
				"version_metadata":"",
				"version_string":"1.0.0"
			},
			"tags":{
				"adds_equipment":PoolStringArray([]),
				"adds_events":PoolStringArray([]),
				"adds_gameplay_mechanics":PoolStringArray([]),
				"adds_ships":PoolStringArray([]),
				"allow_achievements":false,
				"fun":false,
				"handle_extra_crew":24,
				"is_library_mod":false,
				"library_hidden_by_default":true,
				"overhaul":false,
				"quality_of_life":false,
				"uses_hevlib_research":false,
				"visual":false,
				"language":PoolStringArray(["en"]),
				"user_interface":false
			},
			"links":{
				"github":"https://discord.com/channels/426287934870781952/1067385553261166602",
				"discord":"https://discord.gg/dv",
				"nexus":"https://www.nexusmods.com/games/dvringsofsaturn",
				"donations":"https://store.steampowered.com/app/846030/DV_Rings_of_Saturn/",
				"wiki":"https://delta-v.kodera.pl/index.php/Main_Page",
				"bug_reports":"",
				"custom_links":{}
			},
			"configs":{
				
			},
			"manifest_definitions":{
				"manifest_version":2.1,
				"dependancy_mod_ids":[],
				"conflicting_mod_ids":[],
				"complementary_mod_ids":[],
			}
		}
	},
	"zip":""
}
