extends Node

const SHIP_MODIFY = {
	"SHIP_AT225":{
		"middleLeft":{
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -69, -71 )"
				}
			]
		},
		"middleRight":{
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"SYSTEM_PDT-R":[
				{
					"property":"position",
					"value":"Vector2( 69, -71 )"
				}
			]
		},
		"leftBay1":{
			"SYSTEM_PDMWG-L":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		},
		"rightBay1":{
			"SYSTEM_PDMWG-R":[
				{
					"property":"position",
					"value":"Vector2( 2200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-R":[
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"SYSTEM_PDT-R":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		},
		"leftBay2":{
			"SYSTEM_PDMWG-L":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		},
		"rightBay2":{
			"SYSTEM_PDMWG-R":[
				{
					"property":"position",
					"value":"Vector2( 2200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-R":[
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"SYSTEM_PDT-R":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		},
		"leftBay3":{
			"SYSTEM_PDMWG-L":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		},
		"rightBay3":{
			"SYSTEM_PDMWG-R":[
				{
					"property":"position",
					"value":"Vector2( 2200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-R":[
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"SYSTEM_PDT-R":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
		}
	},
	"SHIP_COTHON":{
		"left":{
			"SYSTEM_HUNK-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			]
		},
		"right":{
			"SYSTEM_HUNK-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			]
		},
		"leftBack":{
			"SYSTEM_PDMWG-L":[
				{
					"property":"position",
					"value":"Vector2( -150, 180 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -146, 165 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				},
				{
					"property":"z_index",
					"value":"18"
				}
			]
		},
		"rightBack":{
			"SYSTEM_PDMWG-R":[
				{
					"property":"position",
					"value":"Vector2( 150, 180 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( 146, 165 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				},
				{
					"property":"z_index",
					"value":"18"
				}
			]
		}
	},
	"SHIP_PROSPECTOR":{
		"left":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_ACTEMD14":[
				{
					"property":"position",
					"value":"Vector2( -15, 0 )"
				},
				{
					"property":"rotation",
					"value":"-0.0174533"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 52, -100 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -52, -100 )"
				}
			],
			"SYSTEM_HUNK-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 176 )"
				}
			],
			"SYSTEM_EXMONO-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			]
		},
		"right":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_ACTEMD14":[
				{
					"property":"position",
					"value":"Vector2( 15, 0 )"
				},
				{
					"property":"rotation",
					"value":"0.0174533"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 52, -100 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -52, -100 )"
				}
			],
			"SYSTEM_HUNK-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 176 )"
				}
			],
			"SYSTEM_EXMONO-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			]
		}
	},
	"SHIP_PROSPECTOR_BALD":{
		"middleLeft":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 68 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_EXMONO-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			]
		},
		"middleRight":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 68 )"
				}
			],
			"SYSTEM_EXMONO-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			]
		}
	},
	"SHIP_PROSPECTOR_FAT":{
		"left":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 42, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"SYSTEM_ACTEMD14":[
				{
					"property":"position",
					"value":"Vector2( -15, 0 )"
				},
				{
					"property":"rotation",
					"value":"-0.0174533"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 52, -100 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -52, -100 )"
				}
			],
			"SYSTEM_EXMONO-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				}
			]
		},
		"right":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -42, 60 )"
				}
			],
			"SYSTEM_ACTEMD14":[
				{
					"property":"position",
					"value":"Vector2( -15, 0 )"
				},
				{
					"property":"rotation",
					"value":"-0.0174533"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 52, -100 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( -52, -100 )"
				}
			],
			"SYSTEM_EXMONO-R":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				}
			]
		},
	},
	"SHIP_PROSPECTOR_VP":{
		"left":{
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 50, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -50, 60 )"
				}
			],
		},
		"right":{
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 50, 60 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( -50, 60 )"
				}
			],
		},
	},
	"SHIP_EIME":{
		"left":{
			"SYSTEM_EXSTORAGE-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_CLAIM-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_SCOOP-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_EXMONO-L":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
		},
		"right":{
			"SYSTEM_EXSTORAGE-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_CLAIM-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_SCOOP-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"SYSTEM_EXMONO-R":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
		},
	},
	"SHIP_OCP209":{
		"mainLeft":{
			"SYSTEM_SALVAGE_ARM":[
				{
					"property":"flip",
					"value":"true"
				},
				{
					"property":"feedVelocity",
					"value":"Vector2( -140, -280 )"
				},
			]
		},
		"mainRight":{
			"SYSTEM_SALVAGE_ARM":[
				{
					"property":"feedVelocity",
					"value":"Vector2( 140, -280 )"
				},
			]
		},
	},
	"SHIP_TRTL_K44":{
		"leftBack":{
			"SYSTEM_HUNK-L":[
				{
					"property":"position",
					"value":"Vector2( -40, 222 )"
				},
				{
					"property":"rotation",
					"value":"-0.523599"
				}
			],
			"SYSTEM_PDT-L":[
				{
					"property":"position",
					"value":"Vector2( -124, 211 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				},
			]
		},
		"rightBack":{
			"SYSTEM_HUNK-R":[
				{
					"property":"position",
					"value":"Vector2( 40, 222 )"
				},
				{
					"property":"rotation",
					"value":"0.523599"
				}
			],
			"SYSTEM_PDT-R":[
				{
					"property":"position",
					"value":"Vector2( 124, 211 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				}
			]
		}
	}
}
