extends Node

const SHIP_TEMPLATES = {
	"SHIP_AT225":{
		"middleLeft":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -69, -71 )"
				}
			]
		},
		"middleRight":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 69, -71 )"
				}
			],
		},
		"leftBay1":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"LEFT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( -172, 142 )"
				},
				{
					"property":"rotation",
					"value":"-1.5708"
				},
			]
		},
		"leftBay2":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"LEFT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( -172, 142 )"
				},
				{
					"property":"rotation",
					"value":"-1.5708"
				},
			]
		},
		"leftBay3":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -190, 0 )"
				},
				{
					"property":"rotation",
					"value":"-1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"LEFT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( -172, 142 )"
				},
				{
					"property":"rotation",
					"value":"-1.5708"
				},
			]
		},
		"rightBay1":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"RIGHT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( 172, 142 )"
				},
				{
					"property":"rotation",
					"value":"1.5708"
				},
			]
		},
		"rightBay2":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"RIGHT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( 172, 142 )"
				},
				{
					"property":"rotation",
					"value":"1.5708"
				},
			]
		},
		"rightBay3":{
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 190, 0 )"
				},
				{
					"property":"rotation",
					"value":"1.0472"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"RIGHT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 200, 81 )"
				},
				{
					"property":"z_index",
					"value":"27"
				}
			],
			"NANODRONES":[
				{
					"property":"position",
					"value":"Vector2( 172, 142 )"
				},
				{
					"property":"rotation",
					"value":"1.5708"
				},
			]
		},
	},
	"SHIP_COTHON":{
		"left":{
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"0.174533"
				}
			]
		},
		"right":{
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 80 )"
				},
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			]
		},
		"leftBack":{
			"LEFT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -150, 180 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"rotation",
					"value":"-0.174533"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -146, 165 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				},
				{
					"property":"z_index",
					"value":"18"
				}
			]
		},
		"rightBack":{
			"RIGHT_MIKE_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 150, 180 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"command",
					"value":"\"\""
				},
				{
					"property":"passFireAsCommand",
					"value":"\"\""
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"rotation",
					"value":"0.174533"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 146, 165 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				},
				{
					"property":"z_index",
					"value":"18"
				}
			]
		}
	},
	"SHIP_PROSPECTOR":{
		"left":{
			"CARGO_CONTAINERS":[
				{
					"property":"position",
					"value":"Vector2( 48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( 60, 60 )"
				}
			],
			"GIMBALS":[
				{
					"property":"position",
					"value":"Vector2( -15, 0 )"
				},
				{
					"property":"rotation",
					"value":"-0.0174533"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"position",
					"value":"Vector2( 52, -100 )"
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 176 )"
				}
			]
		},
		"right":{
			"CARGO_CONTAINERS":[
				{
					"property":"position",
					"value":"Vector2( -48, -86 )"
				},
				{
					"property":"z_index",
					"value":"-10"
				}
			],
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( -60, 60 )"
				}
			],
			"GIMBALS":[
				{
					"property":"position",
					"value":"Vector2( 15, 0 )"
				},
				{
					"property":"rotation",
					"value":"0.0174533"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"position",
					"value":"Vector2( -52, -100 )"
				}
			],
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 176 )"
				}
			]
		}
	},
	"SHIP_PROSPECTOR_VP":{
		"left":{
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( 50, 60 )"
				}
			],
		},
		"right":{
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( -50, 60 )"
				}
			],
		},
	},
	"SHIP_EIME":{
		"left":{
			"CARGO_CONTAINERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"CRADLES":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
		},
		"right":{
			"CARGO_CONTAINERS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"CRADLES":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"CLAIM_BEACONS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
			"MINING_COMPANIONS":[
				{
					"property":"position",
					"value":"Vector2( 0, 64 )"
				}
			],
		},
	},
	"SHIP_OCP209":{
		"mainLeft":{
			"MANIPULATION_ARMS":[
				{
					"property":"flip",
					"value":"true"
				},
				{
					"property":"feedVelocity",
					"value":"Vector2( 0, -280 )"
				},
			]
		},
		"mainRight":{
			"MANIPULATION_ARMS":[
				{
					"property":"feedVelocity",
					"value":"Vector2( 0, -280 )"
				},
			]
		},
	},
	"SHIP_TRTL_K44":{
		"leftBack":{
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( -40, 222 )"
				},
				{
					"property":"rotation",
					"value":"-0.523599"
				}
			],
			"LEFT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( -124, 211 )"
				},
				{
					"property":"rotation",
					"value":"-2.0944"
				},
			]
		},
		"rightBack":{
			"IMPACT_ABSORBERS":[
				{
					"property":"position",
					"value":"Vector2( 40, 222 )"
				},
				{
					"property":"rotation",
					"value":"0.523599"
				}
			],
			"RIGHT_WEAPON_TURRETS":[
				{
					"property":"position",
					"value":"Vector2( 124, 211 )"
				},
				{
					"property":"rotation",
					"value":"2.0944"
				}
			]
		}
	}
}
