extends Node

const TEMPLATES = {
	"CENTER_WEAPON_TURRETS":{
		"equipment":[
			"SYSTEM_PDTL",
			"SYSTEM_PDT",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-15)"
			}
		]
	},
	"CENTER_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-16)"
			}
		]
	},
	"LEFT_WEAPON_TURRETS":{
		"equipment":[
			"SYSTEM_PDT-L",
			"SYSTEM_PDTL-L"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-71,19)"
			},
			{
				"property":"rotation",
				"value":"-0.523599"
			},
		]
	},
	"LEFT_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG-L"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-140,60)"
			},
			{
				"property":"rotation",
				"value":"-1.0472"
			},
		]
	},
	"RIGHT_WEAPON_TURRETS":{
		"equipment":[
			"SYSTEM_PDT-R",
			"SYSTEM_PDTL-R"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(71,19)"
			},
			{
				"property":"rotation",
				"value":"0.523599"
			},
		]
	},
	"RIGHT_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG-R"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(140,60)"
			},
			{
				"property":"rotation",
				"value":"1.0472"
			},
		]
	},
	"CRADLES":{
		"equipment":[
			"SYSTEM_EXSTORAGE-L",
			"SYSTEM_EXSTORAGE-R",
			"SYSTEM_CLAIM-L",
			"SYSTEM_CLAIM-R",
			"SYSTEM_SCOOP-L",
			"SYSTEM_SCOOP-R",
			"SYSTEM_HUNK-L",
			"SYSTEM_HUNK-R",
			"SYSTEM_EXMONO-L",
			"SYSTEM_EXMONO-R",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,196)"
			}
		]
	},
	"PLASMATHROWER_LOW":{
		"equipment":[
			"SYSTEM_EINAT",
			"SYSTEM_IROH"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,2)"
			}
		]
	},
	"PLASMATHROWER_HIGH":{
		"equipment":[
			"SYSTEM_EINAT"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-1,2)"
			}
		]
	},
	"MASSDRIVERS":{
		"equipment":[
			"SYSTEM_EMD14",
			"SYSTEM_EMD17RF",
			"SYSTEM_RAILTOR",
			"SYSTEM_ACTEMD14",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-30)"
			}
		]
	},
	"MANIPULATION_ARMS":{
		"equipment":[
			"SYSTEM_SALVAGE_ARM",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,130)"
			}
		]
	},
	"ORE_NANODRONES":{
		"equipment":[
			"SYSTEM_DND_TS",
			"SYSTEM_DND_HAUL"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,50)"
			}
		]
	},
	"FIXED_MICROWAVES":{
		"equipment":[
			"SYSTEM_MWG"
		],
		"data":[]
	},
	"NANODRONES":{
		"equipment":[
			"SYSTEM_DND_TS",
			"SYSTEM_DND_HAUL",
			"SYSTEM_DND_FIX"
		],
		"data":[]
	},
	"LASERS":{
		"equipment":[
			"SYSTEM_CL150",
			"SYSTEM_CL600P",
			"SYSTEM_ACL200P",
			"SYSTEM_PDTL",
			"SYSTEM_PDTL-L",
			"SYSTEM_PDTL-R"
		],
		"data":[]
	},
	"GIMBALS":{
		"equipment":[
			"SYSTEM_ACL200P",
			"SYSTEM_ACTEMD14"
		],
		"data":[]
	},
	"TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG",
			"SYSTEM_PDMWG-L",
			"SYSTEM_PDMWG-R",
			"SYSTEM_PDT-R",
			"SYSTEM_PDT-L",
			"SYSTEM_PDT",
			"SYSTEM_PDTL",
			"SYSTEM_PDTL-L",
			"SYSTEM_PDTL-R",
		],
		"data":[]
	},
	"FRONT_FACING_WEAPONS":{
		"equipment":[
			"SYSTEM_MWG",
			"SYSTEM_CL150",
			"SYSTEM_CL600P",
			"SYSTEM_EMD14",
			"SYSTEM_EMD17RF",
			"SYSTEM_RAILTOR",
			"SYSTEM_ACTEMD14",
			"SYSTEM_ACL200P",
			"SYSTEM_SYNCHRO-L",
			"SYSTEM_SYNCHRO-R",
			"SYSTEM_IROH"
		],
		"data":[]
	},
	"SYNCHROTRONS":{
		"equipment":[
			"SYSTEM_SYNCHRO-R",
			"SYSTEM_SYNCHRO-L"
		],
		"data":[]
	},
	"CARGO_CONTAINERS":{
		"equipment":[
			"SYSTEM_EXMONO-L",
			"SYSTEM_EXMONO-R",
			"SYSTEM_EXSTORAGE-L",
			"SYSTEM_EXSTORAGE-R"
		],
		"data":[]
	},
	"CONTAINERS":{
		"equipment":[
			"SYSTEM_EXMONO-L",
			"SYSTEM_EXMONO-R",
			"SYSTEM_EXSTORAGE-L",
			"SYSTEM_EXSTORAGE-R",
			"SYSTEM_SCOOP-R",
			"SYSTEM_SCOOP-L"
		],
		"data":[]
	},
	"MINING_COMPANIONS":{
		"equipment":[
			"SYSTEM_SCOOP-R",
			"SYSTEM_SCOOP-L"
		],
		"data":[]
	},
	"IMPACT_ABSORBERS":{
		"equipment":[
			"SYSTEM_HUNK-R",
			"SYSTEM_HUNK-L"
		],
		"data":[]
	},
	"CLAIM_BEACONS":{
		"equipment":[
			"SYSTEM_CLAIM-L",
			"SYSTEM_CLAIM-R"
		],
		"data":[]
	},
	"RAILGUNS":{
		"equipment":[
			"SYSTEM_RAILTOR",
			"SYSTEM_PDT-R",
			"SYSTEM_PDT-L",
			"SYSTEM_PDT"
		],
		"data":[]
	},
	"COILGUNS":{
		"equipment":[
			"SYSTEM_EMD14",
			"SYSTEM_EMD17RF",
			"SYSTEM_ACTEMD14"
		],
		"data":[]
	}
}
