extends Node

const TEMPLATES = {
	"CENTER_TURRETS":{
		"equipment":[
			"SYSTEM_PDTL",
			"SYSTEM_PDT",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-15)"
			}
		]
	},
	"CENTER_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG",
			"SYSTEM_MWG"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-16)"
			}
		]
	},
	"LEFT_TURRETS":{
		"equipment":[
			"SYSTEM_PDT-L",
			"SYSTEM_PDTL-L"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-71,19)"
			},
			{
				"property":"rotation",
				"value":"-0.523599"
			},
		]
	},
	"LEFT_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG-L"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-140,60)"
			},
			{
				"property":"rotation",
				"value":"-1.0472"
			},
		]
	},
	"RIGHT_TURRETS":{
		"equipment":[
			"SYSTEM_PDT-R",
			"SYSTEM_PDTL-R"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(71,19)"
			},
			{
				"property":"rotation",
				"value":"0.523599"
			},
		]
	},
	"RIGHT_MIKE_TURRETS":{
		"equipment":[
			"SYSTEM_PDMWG-R"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(140,60)"
			},
			{
				"property":"rotation",
				"value":"1.0472"
			},
		]
	},
	"CRADLES":{
		"equipment":[
			"SYSTEM_EXSTORAGE-L",
			"SYSTEM_EXSTORAGE-R",
			"SYSTEM_CLAIM-L",
			"SYSTEM_CLAIM-R",
			"SYSTEM_SCOOP-L",
			"SYSTEM_SCOOP-R",
			"SYSTEM_HUNK-L",
			"SYSTEM_HUNK-R",
			"SYSTEM_EXMONO-L",
			"SYSTEM_EXMONO-R",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,196)"
			}
		]
	},
	"PLASMATHROWER_LOW":{
		"equipment":[
			"SYSTEM_EINAT",
			"SYSTEM_IROH"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,2)"
			}
		]
	},
	"PLASMATHROWER_HIGH":{
		"equipment":[
			"SYSTEM_EINAT"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(-1,2)"
			}
		]
	},
	"MASSDRIVERS":{
		"equipment":[
			"SYSTEM_EMD14",
			"SYSTEM_EMD17RF",
			"SYSTEM_RAILTOR",
			"SYSTEM_ACTEMD14",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,-30)"
			}
		]
	},
	"MANIPULATION_ARMS":{
		"equipment":[
			"SYSTEM_SALVAGE_ARM",
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,130)"
			}
		]
	},
	"ORE_NANODRONES":{
		"equipment":[
			"SYSTEM_DND_TS",
			"SYSTEM_DND_HAUL"
		],
		"data":[
			{
				"property":"position",
				"value":"Vector2(0,50)"
			}
		]
	},
}
