const RPC_EXTRA_STATES = {
	"ring":[
		{
			"text":"HEVLIB_DISCORDRPC_SECONDARY_CARGOVALUE",
			"sensors":[
				{
					"sensor":"cargo.value",
					"func_object_path":"CurrentGame",
					"func_method_name":"formatThousandsWithDecimals",
					"extra_operands":[2],
					"fallback":"unknown"
				}
			]
		},
		{
			"text":"HEVLIB_DISCORDRPC_SECONDARY_DEPTH",
			"sensors":[
				{
					"sensor":"diveDepth",
					"func_object_path":"CurrentGame",
					"func_method_name":"formatThousandsWithDecimals",
					"extra_operands":[1],
					"fallback":"unknown"
				}
			]
		},
	],
	"enceladus_prime":[
		{
			"text":"HEVLIB_DISCORDRPC_SECONDARY_DATETIME",
			"function_outputs":[
				{
					"name":"dateTime",
					"func_object_path":"res://HevLib/scenes/rpc/secondary_calls.gd",
					"func_method_name":"get_timestamp",
					"extra_operands":[]
				}
			]
		},
	],
	"title_screen":[]
}
